services:
  postgres:
    image: postgres:16
    container_name: pokemon-trades-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-pokemon_trades}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
